// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlI8w16g3T6ofhVjtIrOXVTRqapU1E3jA',
    appId: '1:673739515848:web:f5b5864c24506cd89602fd',
    messagingSenderId: '673739515848',
    projectId: 'daily-prayer-5b8ff',
    authDomain: 'daily-prayer-5b8ff.firebaseapp.com',
    storageBucket: 'daily-prayer-5b8ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlAkfZhWY11D00N6FiByo10fyO84aU6xw',
    appId: '1:673739515848:android:fca0dbb5d174598a9602fd',
    messagingSenderId: '673739515848',
    projectId: 'daily-prayer-5b8ff',
    storageBucket: 'daily-prayer-5b8ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiAS00yki9sHtlkZwH6IAMGB_3o33Q15Q',
    appId: '1:673739515848:ios:0ce691f08d945bdf9602fd',
    messagingSenderId: '673739515848',
    projectId: 'daily-prayer-5b8ff',
    storageBucket: 'daily-prayer-5b8ff.appspot.com',
    iosBundleId: 'com.example.dailyPrayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiAS00yki9sHtlkZwH6IAMGB_3o33Q15Q',
    appId: '1:673739515848:ios:f688e448cba33cd79602fd',
    messagingSenderId: '673739515848',
    projectId: 'daily-prayer-5b8ff',
    storageBucket: 'daily-prayer-5b8ff.appspot.com',
    iosBundleId: 'com.example.dailyPrayer.RunnerTests',
  );
}
